# Generated by Django 5.1.7 on 2025-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_Name',
            field=models.CharField(default='default_username', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='default_firstname', max_length=70),
            preserve_default=False,
        ),
    ]
